#!/bin/sh

# Supported Themes
#   dracula
#   nord
#   tokyonight
export THEME=tokyonight

case $THEME in
	dracula)
		export THEME_BG=282a36
		export THEME_FG=f8f8f2
		export THEME_GREEN=50fa7b
		export THEME_YELLOW=f1fa8c
		export THEME_BLUE=bd93f9
		;;
	nord)
		export THEME_BG=2e3440
		export THEME_FG=d8dee9
		export THEME_GREEN=a3be8c
		export THEME_YELLOW=ebcb8b
		export THEME_BLUE=81a1c1
		;;
	tokyonight)
		export THEME_BG=24283b
		export THEME_FG=c0caf5
		export THEME_GREEN=9ece6a
		export THEME_YELLOW=e0af68
		export THEME_BLUE=7aa2f7
		;;
esac

wmname LG3D

pkill dunst
pkill picom
pkill polybar
pkill sxhkd
pkill xautolock

bspc config window_gap 0

bspc monitor DVI-D-0 -d 1
bspc monitor HDMI-A-0 -d 2 3 4 5 6 7 8 9
bspc config window_gap 20

dunst &
nm-applet &
picom -f &
polybar main &
SXHKD_SHELL=/bin/sh sxhkd &

nitrogen --restore

xautolock -time 5 -locker ~/.config/bspwm/lock.sh -detectsleep &

bspc config border_width        0
bspc config single_monocle      true

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus   true

bspc rule -a firefox desktop=1 follow=on
bspc rule -a firefoxdeveloperedition desktop=1 follow=on
bspc rule -a Alacritty desktop=2 follow=on
bspc rule -a Slack desktop=3 follow=on
bspc rule -a KeePassXC desktop=3 follow=on
bspc rule -a Spotify desktop=4 follow=on
bspc rule -a pinentry-gtk-2 state=floating
bspc rule -a AlacrittyFloating desktop=2 follow=on state=floating
bspc rule -a Peek state=floating

bsp-layout set tall 2 --master-size 0.53
