#!/bin/sh

# Supported Themes
#   dracula
#   nord
#   tokyonight
export THEME=tokyonight
. $HOME/.config/themes/$THEME.theme

wmname LG3D

pkill dunst
pkill picom
pkill polybar
pkill sxhkd
pkill xautolock
pkill polkit-gnome-authentication-agent-1

bspc config window_gap 0

bspc monitor DVI-D-0 -d 1 9
bspc monitor DisplayPort-0 -d 2 3 4 5 6 7 8
bspc config window_gap 20

dunst &
nm-applet &
picom -f &
polybar main &
SXHKD_SHELL=/bin/sh sxhkd &
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

nitrogen --restore

xautolock -time 5 -locker ~/.config/bspwm/lock.sh -detectsleep &

sed "s/^colors: \*.*/colors: *$THEME/" $HOME/.config/alacritty/alacritty.yml

bspc config border_width        0
bspc config single_monocle      true

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config pointer_follows_monitor true
bspc config pointer_follows_focus   true

bspc config external_rules_command $HOME/.config/bspwm/ext-rules.sh

bsp-layout set tall 2 --master-size 0.53
